### ISSUE TITLE
Two warnings in module `Spork.EventQueue`

### ISSUE THREAD

**Issue by dederer** [natefaubion/purescript-spork#11]
Two warnings in module `Spork.EventQueue`:

1. Type variable `a` is ambiguous, since it is unused in the polymorphic type which introduces it.

https://github.com/natefaubion/purescript-spork/blob/17dbd796cbd2dbab5849b798230e71a55a45e119/src/Spork/EventQueue.purs#L52

2. Type variable `s` is ambiguous, since it is unused in the polymorphic type which introduces it.

https://github.com/natefaubion/purescript-spork/blob/17dbd796cbd2dbab5849b798230e71a55a45e119/src/Spork/EventQueue.purs#L83

**Comment by natefaubion** [comment]
https://github.com/natefaubion/purescript-spork/commit/ea422579997a3bfcf83a4d5dbfd9c59077d249c9 Thanks. These locationless warnings drive me nuts 😭
