### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by alpacaaa** [natefaubion/purescript-spork#18]
Is there a way to use SVG out of the box? I've had some success copy pasting some code from [this issue](https://github.com/slamdata/purescript-halogen/issues/363) but I don't understand enough about what's going on to submit a PR.

Thanks!

**Comment by natefaubion** [comment]
I think the only thing that is required is that SVG elements need the appropriate namespace. https://github.com/natefaubion/purescript-spork/blob/master/src/Spork/Html/Core.purs#L138 The default `elem` creates an `ElemSpec` with no namespace (`Nothing`). For SVG we should create one with `Just (Namespace "http://www.w3.org/2000/svg")`.

**Comment by alpacaaa** [comment]
Yep, that does it. Would you accept a PR that adds a `elemWithNS` function?

**Comment by natefaubion** [comment]
Yes, and a matching one for `keyed`.
