### ISSUE TITLE
How to run the todomvc example

### ISSUE THREAD

**Issue by marick** [natefaubion/purescript-spork#25]
I ran the following:

```
npm install
bower install
npm run example:all
cd examples/todo-mvc/
open index.html
```

I get a blank screen and this in the console:

```
SecurityError (DOM Exception 18): The operation is insecure.
```

This was in Safari 11.0.1,  OS X 10.11.6

Full exception below: 
<img width="422" alt="screen shot 2018-03-29 at 6 43 51 pm" src="https://user-images.githubusercontent.com/71909/38118616-9127402c-3381-11e8-87eb-4ea8a91a4121.png">

**Comment by natefaubion** [comment]
I wonder if it needs to be served from a dev server.

**Comment by natefaubion** [comment]
Latest Safari has a a restriction that disables `localStorage` for local files. It either needs to be served through a local server, or you can temporarily disable the restriction in the dev menu.

**Comment by natefaubion** [comment]
A useful enhancement for examples would be to have an npm script for running a local server and also having an index file with descriptions.

**Comment by marick** [comment]
My pull request doesn't do anything with servers. I don't know what you mean by "index file with descriptions". If enlightened, I would provide them.

**Comment by natefaubion** [comment]
I just mean launching a static server (like https://www.npmjs.com/package/http-server maybe), with an `examples/index.html` file that has titles and descriptions of the examples with links.

**Comment by marick** [comment]
I'm not sure what that adds to the instructions I put in the pull request. Something like `elm-reactor` would be nice, but it seems out of scope...

**Comment by natefaubion** [comment]
I'm not suggesting you add it for your PR, just that it would be a convenient showcase and solve the devtool problem :)
