### ISSUE TITLE
Would it be safe to use "mutable array" inside `EventQueue`?

### ISSUE THREAD

**Issue by paluh** [natefaubion/purescript-spork#33]
Currently `EventQueue` uses `queue :: Ref (Array i)` which is quite inefficient. Do you think that it can be safely replaced by something like "mutable array reference"?

**Comment by paluh** [comment]
To be honest we would need something like mutable `queue`... So it is not as trivial to provide it as a mutable array :-)

**Comment by natefaubion** [comment]
I think this is probably a premature optimization regardless. This usually only has a handful of things in it max. It’s very unlikely to be a bottleneck.

**Comment by paluh** [comment]
> I think this is probably a premature optimization regardless.

You are probably right. Thanks!
